version: "3.9"
services:
  app:
    container_name: dtcygan-app
    build:
      context: .
    image: dtcygan:latest
    working_dir: /workspace
    volumes:
      - .:/workspace
    tty: true
    stdin_open: true
    command: bash